### ISSUE TITLE
更新后mirai后，bot无法连接

### ISSUE THREAD

**Issue by SpadeGod** [ElpsyCN/el-bot-js#15]
![image](https://user-images.githubusercontent.com/17895227/122187841-005cef80-cec2-11eb-9429-55f1b366bf19.png)

mirai版本信息如图，早上更新了一下mirai，机器人就无法启动了。报响应失败，是不是mirai改了相关API导致的啊？求大神解答，报错信息如下。

![image](https://user-images.githubusercontent.com/17895227/122188161-474ae500-cec2-11eb-923e-7d3fe5ba43c2.png)

**Comment by SpadeGod** [comment]
el-bot我更新最新版也没用，改端口也试过，都无法解决

**Comment by YunYouJun** [comment]
还没有测试过，mirai 的这个是 dev 版吧，先尽量使用稳定版吧。可能 API 有所变动。

**Comment by YunYouJun** [comment]
问题应该解决了吧。
