### ISSUE TITLE
无法使用 ctx.mirai.api

### ISSUE THREAD

**Issue by Mister-Hope** [ElpsyCN/el-bot-js#16]
请问使用 ctx.mirai.api 需要额外条件么？

我写了个插件，全部代码如下，监听的消息是有效的，日志也可以正常输出，调用自带的 reply 方法也没问题。
但在调用 `mirai.api.sendFriendMessage`  ` mirai.api.kick` `mirai.api.recall` `mirai.api.mute` 会出现如下错误

```
[mirai-api-http] [error] Code 5: 发送消息目标不存在(指定对象不存在)
[mirai-api-http] [error] Code 10: 无操作权限，指 Bot 没有对应操作的限权
[mirai-api-http] [error] Code 10: 无操作权限，指 Bot 没有对应操作的限权
```

我看代码中sessionKey是自动绑定的，这些方法也是很简单的wrapper，所以感觉不是这里的问题。我还查看了官方的插件，并没有发现类似api的调用操作示例。
请问我是否需要额外在console端授权bot? 还是我需要进行其他操作？感谢解答。

注: 我确定bot是管理员而且是通知者的好友。

```ts
import Bot from "el-bot";
import { Member, Group } from "mirai-ts/dist/types/contact";

type Action = "recall" | "mute" | "kick";

interface ForbiddenConfigItem {
  name: string;
  action: Action[];
  /**
   * @default 600
   */
  muteTime?: number;
  plain?: string[];
  exact?: string[];
  reg?: string[];
  hint?: string;
  notify?: boolean;
}

interface ForbiddenConfig {
  config: ForbiddenConfigItem[];
  notify: number[];
}

const getActionName = (action: Action[] = []): string => {
  const map: Record<Action, string> = {
    mute: "禁言",
    recall: "撤回",
    kick: "踢出",
  };

  return action.map((item) => map[item]).join("+");
};

const getGroupName = (group: Group) => `群 ${group.name}(${group.id})`;
const getMemberName = (member: Member) => `${member.memberName}(${member.id})`;

export default (ctx: Bot) => {
  const { el, logger, mirai, status } = ctx;
  const { listen } = el.bot;
  const { config, notify } = el.bot.forbidden as ForbiddenConfig;

  mirai.on("GroupMessage", (msg) => {
    // only check messages in listeners
    if (status.isListening(msg.sender, listen)) {
      const { sender } = msg;
      const groupName = getGroupName(sender.group);
      const memberName = getMemberName(sender);

      for (const item of config) {
        if (
          item.plain?.some((word) => msg.plain.includes(word)) ||
          item?.exact?.some((word) => word === msg.plain) ||
          item?.reg?.some((word) => new RegExp(word).exec(msg.plain))
        ) {
          logger.warn(
            `${msg.plain} 命中 ${item.name} 需要 ${getActionName(item.action)}`
          );

          if (item.notify) {
            notify?.forEach((qqNumber) => {
              mirai.api.sendFriendMessage(
                `${groupName} 的 ${memberName} 发送了 ${msg.plain}，请进行关注！`,
                qqNumber
              );
              // 进行通知
            });
          }

          // 回复提示
          if (item.hint) msg.reply(item.hint);

          // 踢出
          if (item.action.includes("kick")) {
            mirai.api.kick(sender.group.id, msg.sender.id);
            logger.warn(`已从 ${groupName} 踢出 ${memberName} `);
          } else {
            // 撤回
            if (item.action.includes("recall")) {
              mirai.api.recall(msg);
              logger.warn(`已在 ${groupName} 撤回 ${memberName} 的消息`);
            }

            // 禁言
            if (item.action.includes("mute")) {
              mirai.api.mute(sender.group.id, sender.id, item.muteTime || 600);
              logger.warn(
                `已对 ${groupName} 的 ${memberName} 禁言 ${item.muteTime}s`
              );
            }
          }

          break;
        }
      }
    }
  });

  mirai.on("MemberCardChangeEvent", (msg) => {
    const { member } = msg;

    // only check messages in listeners
    if (status.isListening(member, listen)) {
      const memberName = getMemberName(member);
      const groupName = getGroupName(member.group);

      logger.info(
        `${groupName} 的 ${memberName} 修改名片为 ${msg.current} (原为 ${msg.origin})`
      );
    }
  });
};
```

**Comment by YunYouJun** [comment]
`ctx.mirai.api` 使用无额外条件。自动绑定 session，无需额外授权。

**Comment by YunYouJun** [comment]
el-bot 登录的 QQ 是否与 mirai 的 QQ 号一致？无法复现该问题，我的插件均直接调用 api 即可。

**Comment by YunYouJun** [comment]
能否提供下 `el-bot` 版本？ 有可能与 mah 2.0 有关，我测试一下。

**Comment by Mister-Hope** [comment]
el-bot是^0.9.0-alpha.3
mah是2.0.2
我确认登陆的是一个QQ，而且msg.reply 方法是奏效的。

**Comment by YunYouJun** [comment]
> el-bot是^0.9.0-alpha.3
> mah是2.0.2
> 我确认登陆的是一个QQ

Yeah, 我确认这应当与 mah 2.0 有关，（1.0 版本目前没问题），我仅仅启动 mirai 与 mah，并使用 POSTMAN 自行获取 Session，通过 http 调用 mute 方法仍然会出现权限问题。（具体原因还需要继续排查）

**Comment by Mister-Hope** [comment]
您能帮着看一下是再好不过的了。😊

还有一个问题，因为我在做我们学校半官方新生群的管理，主要是为了自动审核和群内消息监控。

我希望能够用匹配入群信息并自动审批那些符合 “省份(遍历) 招生专业(遍历 姓名(2-5中文汉字)" 但是我看您的包装器上没有对应的方法。您有计划添加么？如果没有 mirar.sessionKey 我是可以直接拿来用的是吧？

**Comment by Mister-Hope** [comment]
> > el-bot是^0.9.0-alpha.3
> > mah是2.0.2
> > 我确认登陆的是一个QQ
> 
> Yeah, 我确认这应当与 mah 2.0 有关，（1.0 版本目前没问题），我进启动 mirai 与 mah，并使用 POSTMAN 自行获取 Session，通过 http 调用 mute 方法仍然会出现权限问题。（具体原因还需要继续排查）

收到，感谢👍，那我如果现在想用的话，我应该回退到哪个版本以使用mah 1.12.0呢？因为您似乎一直发在latest

**Comment by YunYouJun** [comment]
> > > el-bot是^0.9.0-alpha.3
> > > mah是2.0.2
> > > 我确认登陆的是一个QQ
> > 
> > 
> > Yeah, 我确认这应当与 mah 2.0 有关，（1.0 版本目前没问题），我进启动 mirai 与 mah，并使用 POSTMAN 自行获取 Session，通过 http 调用 mute 方法仍然会出现权限问题。（具体原因还需要继续排查）
> 
> 收到，感谢👍，那我如果现在想用的话，我应该回退到哪个版本以使用mah 1.12.0呢？

`el-bot@0.8.x` 即可。

**Comment by Mister-Hope** [comment]
好的感谢！我去试试，再次感谢您的回复！另外这是一个非常awesome的项目，应该能帮助我节省很多时间，毕竟千人的新生群实在看不过来。👍

**Comment by YunYouJun** [comment]
> 您能帮着看一下是再好不过的了。😊
> 
> 还有一个问题，因为我在做我们学校半官方新生群的管理，主要是为了自动审核和群内消息监控。
> 
> 我希望能够用匹配入群信息并自动审批那些符合 “省份(遍历) 招生专业(遍历 姓名(2-5中文汉字)" 但是我看您的包装器上没有对应的方法。您有计划添加么？如果没有 mirar.sessionKey 我是可以直接拿来用的是吧？

对应的方法是指？

如果是指对消息内容的判断，这种可能过于定制，需要您自行实现。

如果是指对请求的响应，已包装了该方法。可通过 `msg.respond(operate, message)` 形式进行处理。

https://github.com/YunYouJun/mirai-ts/blob/81d786c7f7791cf46892985384f5bb2e7b974c48/src/helper.ts#L78

**Comment by YunYouJun** [comment]
> 收到，感谢👍，那我如果现在想用的话，我应该回退到哪个版本以使用mah 1.12.0呢？因为您似乎一直发在latest

🤣 抱歉，这个是我的疏忽，已修改 `0.8.0-beta.7` 为 `latest`，`0.9.0-alpha.2` 为 `next`。

**Comment by Mister-Hope** [comment]
> > 您能帮着看一下是再好不过的了。😊
> > 还有一个问题，因为我在做我们学校半官方新生群的管理，主要是为了自动审核和群内消息监控。
> > 我希望能够用匹配入群信息并自动审批那些符合 “省份(遍历) 招生专业(遍历 姓名(2-5中文汉字)" 但是我看您的包装器上没有对应的方法。您有计划添加么？如果没有 mirar.sessionKey 我是可以直接拿来用的是吧？
> 
> 对应的方法是指？
> 
> 如果是指对消息内容的判断，这种可能过于定制，需要您自行实现。
> 
> 如果是指对请求的响应，已包装了该方法。可通过 `msg.respond(operate, message)` 形式进行处理。
> 
> https://github.com/YunYouJun/mirai-ts/blob/81d786c7f7791cf46892985384f5bb2e7b974c48/src/helper.ts#L78

啊好的我看看，

**Comment by Mister-Hope** [comment]
您好，我回退到 0.8.0-beta.7 和 mah 1.12.0，`mirai.api.sendFriendMessage` 正常工作了

![image](https://user-images.githubusercontent.com/33315834/126074200-fdf7e84b-eb4b-4e98-9c0f-71e9098ee896.png)

但是 `mirai.api.kick` `mirai.api.recall` `mirai.api.mute` 还是提示

```
[el-bot] [00:02:41] [warn] 肉棒 命中 黄色 需要 踢出
[el-bot] [00:02:41] [warn] 已从 群 备忘(587571287) 踢出 Little Hope(3178522294) 
[mirai-api-http] [error] Code 10: 无操作权限，指 Bot 没有对应操作的限权
[el-bot] [00:03:05] [warn] 激情 命中 疑似黄色 需要 撤回+禁言
[el-bot] [00:03:05] [warn] 已在 群 备忘(587571287) 撤回 Little Hope(3178522294) 的消息
[el-bot] [00:03:05] [warn] 已对 群 备忘(587571287) 的 Little Hope(3178522294) 禁言 86400s
[mirai-api-http] [error] Code 10: 无操作权限，指 Bot 没有对应操作的限权
[mirai-api-http] [error] Code 10: 无操作权限，指 Bot 没有对应操作的限权
```

![image](https://user-images.githubusercontent.com/33315834/126074263-4de306b7-a939-431a-92b3-0869db76d035.png)

您测试用的是mah哪个版本呢？我是否需要退回到 mirar 2.6  和 mah 1.10.0?

Updated:

Postman is not working too.

![image](https://user-images.githubusercontent.com/33315834/126074723-9a549245-e4ce-4618-bd53-ced1ceca3d7e.png)

**Comment by YunYouJun** [comment]
🤣 这不科学，试试重启 mirai？也许与 mirai 权限未正确加载有关系。

**Comment by Mister-Hope** [comment]
好的我试试

**Comment by YunYouJun** [comment]
> 好的我试试

回退 mirai 2.6，和 mah 1.10.0 试试吧，大概率问题出在他们身上。

似乎有类似的 Issue。
https://github.com/mamoe/mirai/issues/1406

**Comment by Mister-Hope** [comment]
好耶！成功了！再次感谢您和您的项目！

```
[el-bot] [12:38:07] [info] 群 东北师范大学2021新生群 (594493757) 收到 三字十七画 的申请，消息为 问题：省份 专业 姓名
答案：山东美术学陈洁
[el-bot] [12:38:07] [info] 申请符合规则，自动同意入群
[el-bot] [12:39:07] [info] 群 东北师范大学2021新生群(594493757) 的 Lu小明. 修改名片 (原为 )
[el-bot] [12:39:11] [info] 群 东北师范大学2021新生群(594493757) 的 20经管 修改名片 (原为 20经济)
[el-bot] [12:40:34] [info] 群 东北师范大学2021新生群(594493757) 的 20四川经管 修改名片 (原为 20经管)
[el-bot] [12:41:02] [info] 群 东北师范大学2021新生群(594493757) 的 666 修改名片 (原为 )
```

**Comment by Mister-Hope** [comment]
好耶！成功了！再次感谢您和您的项目！

```
[el-bot] [12:38:07] [info] 群 东北师范大学2021新生群 (594493757) 收到 三字十七画 的申请，消息为 问题：省份 专业 姓名
答案：山东美术学陈洁
[el-bot] [12:38:07] [info] 申请符合规则，自动同意入群
[el-bot] [12:39:07] [info] 群 东北师范大学2021新生群(594493757) 的 Lu小明. 修改名片 (原为 )
[el-bot] [12:39:11] [info] 群 东北师范大学2021新生群(594493757) 的 20经管 修改名片 (原为 20经济)
[el-bot] [12:40:34] [info] 群 东北师范大学2021新生群(594493757) 的 20四川经管 修改名片 (原为 20经管)
[el-bot] [12:41:02] [info] 群 东北师范大学2021新生群(594493757) 的 666 修改名片 (原为 )
```

**Comment by YunYouJun** [comment]
Yeah, have fun.

> mirai 背锅。
