### ISSUE TITLE
出现404Error错误

### ISSUE THREAD

**Issue by mewhz** [ElpsyCN/el-bot-js#19]
**环境：mirai-api-http-v2.2.0，mcl：使用iTXTech MCL Installer 1.0.3一键安装**
**setting.yml**
![setting](https://user-images.githubusercontent.com/48837161/131877990-ad6edd4e-5be2-4bda-af31-3c429fa15720.png)
**index.js**
![index](https://user-images.githubusercontent.com/48837161/131878116-8c1083f8-b185-4640-a2de-e2be6b816f52.png)
**localhost:8080/about 访问正常**
![about](https://user-images.githubusercontent.com/48837161/131878251-2bf0b33e-88c0-4257-b6ba-c03d1c0e321d.png)
**mirai正常运行**
![mc](https://user-images.githubusercontent.com/48837161/131878275-b0917956-75d8-41b8-86a2-7f347493bd6f.png)
**报错信息**
![bot](https://user-images.githubusercontent.com/48837161/131878286-8180fc50-1793-46c3-93d3-221c3f901ec3.png)
**使用el-bot-template最新releases**
**QQ号填写没有问题**
**复现过程**
> 一键安装mcl后，成功登录QQ，测试localhost:8080/about可以访问通
> 下载el-bot-template，解压到my-bot文件夹，在该文件夹使用npm install el-bot安装库
> 使用npm run start:bot启动后发现缺少包，再次使用npm install 下载
> 重新使用npm run start:bot命令，后发现报404错误

望解答，感谢

**Comment by YunYouJun** [comment]
测试使用 [el-bot-template](https://github.com/ElpsyCN/el-bot-template) 启动无问题，请尝试更新至最新版。

此外端口号建议使用 `4859` 而非 `8080` 以避免与其他常用端口产生冲突。

```yml
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 4859
    cors: ["*"]
```
