### ISSUE TITLE
框架是不是没有ts-load

### ISSUE THREAD

**Issue by loneyclown** [ElpsyCN/el-bot-js#20]
框架是不是没有tscload，如果我自定义插件的入口文件是ts文件，插件就没法正确加载。。。

**Comment by Mister-Hope** [comment]
我的插件是ts，对我来说没什么问题

**Comment by loneyclown** [comment]
> 我的插件是ts，对我来说没什么问题

可以看下你的目录结构和配置吗？

**Comment by YunYouJun** [comment]
我后来尝试和 nest 结合了下。结构可以参考这里 https://github.com/YunYouJun/el-bot/tree/dev/packages/demo 。

**Comment by loneyclown** [comment]
明白了，谢谢。
