### ISSUE TITLE
bot.start() 无法正确链接你的qq

### ISSUE THREAD

**Issue by dongshimou** [ElpsyCN/el-bot-js#21]
> mcl 1.0.3-linux
> net.mamoe:mirai-api-http 2.3.3
> "el-bot": "^0.9.0-beta.5",

[el-bot] [19:16:17] [info] Link Start!
[mirai-api-http] [info] [http] Address: http://localhost:8088
[mirai-api-http] [info] [http] Session: SINGLE_SESSION
[mirai-api-http] [error] Code 6: 指定文件不存在，出现于发送本地图片
[mirai-api-http] [error] 验证失败
[el-bot] [19:16:17] [error] 无法正确链接您的 QQ，请检查 QQ 是否正确！

**Comment by Mister-Hope** [comment]
你的第一反应，难道不应该是思考一下这个么？

```
[mirai-api-http] [error] 验证失败
```

**Comment by YunYouJun** [comment]
请检查 `mirai-api-http` 是否搭建成功，对应端口号下 `/about` 是否可正常访问，对应 QQ 号是否正确。

**Comment by dongshimou** [comment]
确认是正确的...
两边的配置同时设置 `singleMode: false`的时候就没有这个问题了.

我确实只登录了一个bot.按照`mirai-api-http`的说法可以设置.但是设置之后就出现这个问题.

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/144243788-00500fa7-4f1f-4d10-892b-23e4175c9c4d.png)

可以通过直接读取 YAML 的方式保证配置相同。
