### ISSUE TITLE
feature need!  长消息自动分段

### ISSUE THREAD

**Issue by Vivapercuore** [ElpsyCN/el-bot-js#5]
目前腾讯的单条消息限制大约在1000左右

将消息长度进行分页  直接取msg.length即可?  
AT,Image,XML.JSON等类型消息可能需要特殊处理

较为安全的做法: 
消息长度每800长度分一段
体验优化:
msgs[lastPage].length%800 <100 时,和上一页直接合并,防止一个长度非常短的尾页出现

**Comment by YunYouJun** [comment]
AT,Image,XML.JSON 等类型消息就不打算进行处理了……
只针对字符串类型消息长度过长的进行分割。

**Comment by YunYouJun** [comment]
写在 mirai-ts 里了。 https://github.com/YunYouJun/mirai-ts/commit/2fffa127777b885989e4446573d724ce2b502326
已更新 el-bot 依赖及其版本。（v0.5.3）

**Comment by Vivapercuore** [comment]
> AT,Image,XML.JSON 等类型消息就不打算进行处理了……
> 只针对字符串类型消息长度过长的进行分割。

提出是为了防止在复合类型消息的时候对这些类型进行了不安全的操作(不过应该是小概率事件)
例如
msg.reply([
message. Plain(longlongtext),
message.image(),
message. Plain(longlongtext),
message.AT(),
message.image(),
message. Plain(longlongtext),
])

分割点的拆分应该只在Plain 内部进行,  否则拆分点在其他类型内部可能会产生不可预料的错误

******
只是一个提醒

**Comment by YunYouJun** [comment]
Message.Plain 只是将文本消息格式化，就算在内部分割，本质上传出到 mirai-api-http 还是放在一条消息的，所以内部分割没啥用。想要分段只能是切割文本，依次发送。

> [Message.Plain('hello'), Message.Plain('world')] 和 [Message.Plain('hello world')] 最后在 QQ 中的表现是一样的。

所以内部的长度只能由开发者自己控制，我只是在 reply 上加一个语法糖，省去一部分分割操作。
