### ISSUE TITLE
[Bug?] TypeError: msg.isAt is not a function

### ISSUE THREAD

**Issue by fun4wut** [ElpsyCN/el-bot-js#8]
环境：
- Node: 12.18.4
- el-bot: 0.5.14
- mirai-ts: 0.7.8

answer插件在监听私聊消息的时候会报错 `TypeError: msg.isAt is not a function`，看了下，问题出在 https://github.com/YunYouJun/el-bot/blob/dc4d05d0c1ca7cd6fc4fdf43542c2ee9b9ee67d1/src/plugins/answer/index.ts#L89

讲道理由于短路特性应该不会走到 `msg.isAt()`，但是好像就是执行到了这里。
目前我的补救办法是对 `msg.isAt` 是否存在再做一个判断
```js
if (ans.at && msg.isAt && !msg.isAt()) return
```

**Comment by YunYouJun** [comment]
试试 `0.5.15` ? 上次刚修了。

**Comment by fun4wut** [comment]
> 试试 `0.5.15` ? 上次刚修了。

@YunYouJun 唔，升到了0.5.15还是一样的错误

**Comment by YunYouJun** [comment]
尝试用这种方式修复了。

```typescript
if (ans.at) {
  if (!(msg.type === "GroupMessage" && msg.isAt())) return;
}
```

可以升级到 `0.5.16` 试试。

**Comment by fun4wut** [comment]
可以了，感谢
